### PR TITLE
Update for react > 0.14

### PR DESCRIPTION
**Pull request by bitspook**
- Use react-dom instead of react for `findDOMNode` because in react 0.14.x
  it shows a warning, and for react 15.0 it fails

### CODE REVIEW

**Comment by gajus** [comment]
@jxnblk can you add more people as contributors to github/ npm to merge PRs?

**Comment by jxnblk** [comment]
Thanks, but I don't think you don't need React Dom at all for this. In 0.14+ It should be just using refs

**Comment by bitspook** [comment]
Hey,

Yes you're right. Sorry for that. I've updated the PR. I've also added a note to Readme file regarding the requirement of react >= v0.14; please edit it as you please.

**Comment by gajus** [comment]
@jxnblk Hi, can this be merged now?

**Comment by jxnblk** [comment]
Thanks!

**Comment by bitspook** [comment]
Hey @jxnblk , 

Can you please update the version and publish the package on npm?

**Comment by gajus** [comment]
@jxnblk can you add more people as contributors to github/ npm to merge PRs/ release new versions?

**Pull request merged**
